version: '3.8'
services:
  app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DIALECT=postgres
      - HOST=postgres
      - USERNAMEDB=postgres
      - PASSWORDDB=postgres
      - DATABASE=db_express
      - PORT=5432
      - PORT_API=3000
      - SECRET_JWT=SuaChaveSecreta
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_express
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: